models/event-bookingInfo.json, models/place-bookingInfo.json
- Missing properties on `event.bookingInfo`
- Missing properties on `place.bookingInfo`
- `url`, `phone` and `email` properties on `event.bookingInfo`
- `url`, `phone` and `email` properties on `place.bookingInfo`
---
=> Bookinginfo

models/event-status.json, models/event-subEvent.json, models/event.json, models/place-status.json, models/place.json
- Casing of `Available`, `Unavailable`, `TemporarilyUnavailable`
- Example of `bookingInfo` on event and place
=> Small event/place fixes

package.json, yarn.lock
- Updated `spectral` to `6.0.0-alpha3` for OpenAPI 3.1.0 support
=> Update CI automatically via cultuurnet/stoplight-ci

models/event-subEvent-patch.json, reference/entry.json
- Extracted body schema for PATCH /events/{eventId}/subEvents to separate file, which we can then use for validation inside udb3-silex
=> Move body schema for PATCH /events/{eventId}/subEvents to separate file

reference/entry.json
=> Document place details endpoint

reference/entry.json
- Documentation for deprecated `POST /event/{eventId}/major-info` endpoint
- Documentation for deprecated `POST /place/{placeId}/major-info` endpoint
=> Document major-info endpoints

docs/errors.md
- Add error message `id already in use`
---
Ticket: https://jira.uitdatabank.be/browse/III-4142
=> III-4142 Add error message id already in use

reference/entry.json
- `GET /events/{eventId}/calendar-summary` endpoint
- `GET /places/{placeId}/calendar-summary` endpoint
=> III-4275 Document calendar summary endpoints

models/organizer-url-put.json, reference/entry.json
- Added docs for updating the url of an organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4287
=> III-4287 Add docs for updating organizer url

models/organizer-contact-point-put.json, reference/entry.json
- Added docs for updating the contact point information of an organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4290
=> III-4290 Add docs for updating the contact point information of an organizer

reference/entry.json
- Add docs for adding a label to an organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4288
=> III-4288 Add docs for adding a label to an organizer

reference/entry.json
- Added docs for deleting label from organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4289
=> III-4289 Add docs for deleting label from organizer

reference/entry.json
- Added docs for updating organizer name in default language
---
Ticket: https://jira.uitdatabank.be/browse/III-4292
=> III-4292 Add docs for updating organizer name in default language

reference/entry.json
- Added docs for deleting address from organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4294
=> III-4294 Document deleting address from organizer

reference/entry.json
- Documentation for `DELETE /events/{eventId}`
- Documentation for `DELETE /places/{placeId}`
---
Ticket: https://jira.uitdatabank.be/browse/III-4271
=> III-4271 Delete event

reference/entry.json
- Added docs for updating organizer address in default language
---
Ticket: https://jira.uitdatabank.be/browse/III-4293
=> III-4293 Added docs for updating organizer address in default language

reference/entry.json
- Added docs for deleting an organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4291
=> III-4291 Add docs for deleting an organizer

models/organizer-@id.json, models/organizer-completedLanguages.json, models/organizer-contactPoint-put.json, models/organizer-contactPoint.json, models/organizer-created.json, models/organizer-creator.json, models/organizer-hiddenLabels.json, models/organizer-labels.json, models/organizer-languages.json, models/organizer-mainLanguage.json, models/organizer-modified.json, models/organizer-name.json, models/organizer-workflowStatus.json, models/organizer.json, reference/entry.json
- Added docs for the Organizer GET request
---
Ticket: https://jira.uitdatabank.be/browse/III-4284
=> III-4284 Added docs for the Organizer GET request

models/organizer-contactPoint-put.json
- Fixed organizer contact point validation
=> Fix organizer contact point

models/event-availableFrom-put.json, models/place-availableFrom-put.json, reference/entry.json
- Added  docs for updating available of event and place
- Added missing 40x errors for updating audience of an event
---
Ticket: https://jira.uitdatabank.be/browse/III-4227
=> III-4227 Document updating available from on event or place

reference/entry.json
- Added docs for the endpoint to delete the theme of an event
---
Ticket: https://jira.uitdatabank.be/browse/III-4378
=> III-4378 Add docs for the endpoint to delete the theme of an event

models/event-hiddenLabels.json, models/event-labels.json, models/organizer-address.json, models/organizer-contact.json, models/organizer-hiddenLabels.json, models/organizer-labels.json, models/organizer-post.json, models/organizer.json, models/place-address.json, models/place-hiddenLabels.json, models/place-labels.json, reference/entry.json
- Added documentation for the post organizers endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4283
=> III-4283 Document the post organizers endpoint

models/newsArticle.json, reference/entry.json
- Added docs for the news article get requests:
- getting one new article by id
- getting all news articles
---
=> III-4410 Document the news article get request

reference/entry.json
- Added docs for the delete news article endpoint
---
=> III-4410 Document news article delete request

models/newsArticle-post.json, reference/entry.json
- Added body for news article post request
- Added docs for POST news article endpoint
- Added docs for PUT news article endpoint
---
=> III-4410 Document post and put request for news articles

reference/entry.json
- Added query parameters publisher, about and url
---
=> III-4410 Add query parameters publisher, about and url

models/newsArticle-post.json, models/newsArticle.json
- Make all news article properties required (this was validated with the current consumers of the curator API, all properties are always provided so they can become required)
---
=> III-4410 Finetune the news article properties

reference/entry.json
- Added info about the `page` query parameter
- Wrapped result inside `hydra:member` to mimic old API
---
=> III-4410 Add pagination and hydra:member

models/organizer-post.json
- Fix organizer missing website
=> Fix organizer missing website

models/organizer-description-put.json, models/organizer-description.json, models/organizer.json, reference/entry.json
- Added organizer description model for GET request
- Added organizer description model for PUT request
- Document endpoint to update description of organizer in the given language
---
Ticket: https://jira.uitdatabank.be/browse/III-4425
=> III-4425 add description to organizer

models/organizer-image-post.json, models/organizer-images-post.json, models/organizer-images.json, models/organizer.json, reference/entry.json
- Added docs for POST images endpoint on organizers
---
Ticket: https://jira.uitdatabank.be/browse/III-4426
=> III-4426 Add documentation for adding an image to an organizer

reference/entry.json
- Added documentation about endpoint to delete image from organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4428
=> III-4428 Document endpoint to delete image from organizer

models/organizer.json, reference/entry.json
- Added docs for getting an organizer by id 
---
Ticket: https://jira.uitdatabank.be/browse/III-4469
=> III-4469 Add docs for getting an organizer by id

reference/entry.json
- Fixed API URLs by using HTTPS
=> Make sure to use HTTPS to avoid redirects from Apache

reference/entry.json
- Documentation for `POST /events/{eventId}/copies`, as an internal endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4516
=> III-4516 Document endpoint to copy event

models/event-@id.json, models/event-bookingInfo.json, models/event-contactPoint.json, models/event-image.json, models/event-mediaObject.json, models/event-production.json, models/event-sameAs.json, models/event-videos-patch.json, models/event-videos-post.json, models/event-videos.json, models/newsArticle-post.json, models/newsArticle.json, models/organizer-contactPoint-put.json, models/organizer-contactPoint.json, models/organizer-images.json, models/organizer-post.json, models/organizer-url-put.json, models/organizer.json, models/place-@id.json, models/place-bookingInfo.json, models/place-contactPoint.json, models/place-image.json, models/place-mediaObject.json, models/place-sameAs.json, models/place-videos-post.json, models/place-videos.json, reference/entry.json
- Fixed every "url" property so it has `format: uri` and regex `pattern` to check for `http(s)://`
- Fixed `@id` properties so they have a pattern that checks that there is a uuid (v4 or the UDB1 format) at the end
---
Ticket: https://jira.uitdatabank.be/browse/III-4544
=> III-4544 Fix URL properties

reference/entry.json
- Removed faulty xml request body
=> Remove xml request body

reference/entry.json
- Added documentation for `PUT /organizers/{organizerId}`
---
Ticket: https://jira.uitdatabank.be/browse/III-4404
=> III-4404 PUT /organizers/{organizerId}

models/event-post-deprecated.json, reference/entry.json, reference/taxonomy.json
- Added model for the deprecated body of POST event
- Documented the POST event endpoint for both deprecated and new format
---
Ticket: https://jira.uitdatabank.be/browse/III-4368
=> III-4368 Document POST events endpoint
